# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class raceItem(scrapy.Item):
    date = scrapy.Field()
    venue = scrapy.Field()
    race_no = scrapy.Field()
    race_id = scrapy.Field()
    race_type = scrapy.Field()
    name = scrapy.Field()
    prize = scrapy.Field()
    going = scrapy.Field()
    course = scrapy.Field()
    placing = scrapy.Field()
    horse_no = scrapy.Field()
    horse = scrapy.Field()
    horse_url = scrapy.Field()
    jockey = scrapy.Field()
    trainer = scrapy.Field()
    actual_wt = scrapy.Field()
    declared_wt = scrapy.Field()
    draw = scrapy.Field()
    lbw = scrapy.Field()
    running_position = scrapy.Field()
    finish_time = scrapy.Field()
    win_odds = scrapy.Field()

class dividendItem(scrapy.Item):
    date = scrapy.Field()
    venue = scrapy.Field()
    race_no = scrapy.Field()
    race_id = scrapy.Field()
    pool = scrapy.Field()
    winning_combo = scrapy.Field()
    dividend = scrapy.Field()

class sectionalItem(scrapy.Item):
    date = scrapy.Field()
    venue = scrapy.Field()
    race_no = scrapy.Field()
    race_time = scrapy.Field()
    sectional_time = scrapy.Field()
    finishing_order = scrapy.Field()
    horse_no = scrapy.Field()
    horse = scrapy.Field()
    sec1_position = scrapy.Field()
    sec1_lbw = scrapy.Field()
    sec1_time = scrapy.Field()
    sec2_position = scrapy.Field()
    sec2_lbw = scrapy.Field()
    sec2_time = scrapy.Field()
    sec3_position = scrapy.Field()
    sec3_lbw = scrapy.Field()
    sec3_time = scrapy.Field()
    sec4_position = scrapy.Field()
    sec4_lbw = scrapy.Field()
    sec4_time = scrapy.Field()
    sec5_position = scrapy.Field()
    sec5_lbw = scrapy.Field()
    sec5_time = scrapy.Field()
    sec6_position = scrapy.Field()
    sec6_lbw = scrapy.Field()
    sec6_time = scrapy.Field()
    finish_time = scrapy.Field()

class horseInfoItem(scrapy.Item):
    horse_id = scrapy.Field()
    horse = scrapy.Field()
    retired = scrapy.Field()
    rating_url = scrapy.Field()
    distance_url = scrapy.Field()
    trackwork_url = scrapy.Field()
    veterinary_url = scrapy.Field()
    movement_url = scrapy.Field()
    overseas_url = scrapy.Field()
    pedigree_url = scrapy.Field()
    country_origin = scrapy.Field()
    colour_sex = scrapy.Field()
    import_type = scrapy.Field()
    total_stakes = scrapy.Field()
    total_123_starts = scrapy.Field()
    current_stable = scrapy.Field()
    trainer = scrapy.Field()
    owner = scrapy.Field()
    last_rating = scrapy.Field()
    sire = scrapy.Field()
    dam = scrapy.Field()
    dams_sire = scrapy.Field()
    same_sire = scrapy.Field()

class horseFormItem(scrapy.Item):
    horse_id = scrapy.Field()
    horse = scrapy.Field()
    season = scrapy.Field()
    race_id = scrapy.Field()
    race_url = scrapy.Field()
    placing = scrapy.Field()
    date = scrapy.Field()
    course = scrapy.Field()
    distance = scrapy.Field()
    going = scrapy.Field()
    race_class = scrapy.Field()
    draw = scrapy.Field()
    rating = scrapy.Field()
    trainer = scrapy.Field()
    jockey = scrapy.Field()
    lbw = scrapy.Field()
    win_odds = scrapy.Field()
    actual_wt = scrapy.Field()
    running_position = scrapy.Field()
    finish_time = scrapy.Field()
    declared_wt = scrapy.Field()
    gear = scrapy.Field()